package com.kii.extension.ruleengine.demo

import com.kii.extension.ruleengine.thingtrigger.*;


rule "list thing status"
when
	$status:ThingStatus()
then
	System.out.println("thing status:"+$status.getThingID());
end


rule "summary of  true  result:all"
when
	$trigger:Trigger(type =="all")
	accumulate( MatchResult(triggerID==$trigger.triggerID,$thingID:thingID );
                    $thingCount : count($thingID);
                    $thingCount==$trigger.things.size()
                    )
then
	System.out.println("trigger "+$trigger.getTriggerID()+" been fire");
end


rule "summary of  true  result:any"
when
	$trigger:Trigger(type =="any")
	accumulate( MatchResult(triggerID==$trigger.triggerID,$thingID:thingID );
                    $thingCount : count($thingID);
                    $thingCount>=1
                    )
then
	System.out.println("trigger "+$trigger.getTriggerID()+" been fire");
end

rule "summary of  true  result:number"
when
	$trigger:Trigger(type =="number")
	accumulate( MatchResult(triggerID==$trigger.triggerID,$thingID:thingID );
                    $thingCount : count($thingID);
                    $thingCount>=$trigger.number
                    )
then
	System.out.println("trigger "+$trigger.getTriggerID()+" been fire");
end
