package com.kii.extension.ruleengine.demo

import com.kii.extension.ruleengine.thingtrigger.*;



rule "compute the summary of  fieldName value:sum funName"
	no-loop true
when
	$trigger:Trigger(type =="summary")
	$summary:Summary(triggerID==$trigger.triggerID , funName=="sum" )
	accumulate( ThingStatus(thingID memberOf $trigger.things ,$status:values);
                    $value : sum($status.get($summary.getFieldName()))
                    )
    $map:SummaryValueMap(triggerID==$trigger.triggerID)
then
	modify($map){
		setNumber($summary.getSummaryField(),$value);
	};
	System.out.println("compute summary:"+$map.getNumberMap());
end


rule "summary of  true  result:all"
when
	$trigger:Trigger(type =="all")
	accumulate( MatchResult(triggerID==$trigger.triggerID,$thingID:thingID );
                    $thingCount : count($thingID);
                    $thingCount==$trigger.things.size()
                    )
then
	System.out.println("trigger "+$trigger.getTriggerID()+" been fire");
end


rule "summary of  true  result:any"
when
	$trigger:Trigger(type =="any")
	accumulate( MatchResult(triggerID==$trigger.triggerID,$thingID:thingID );
                    $thingCount : count($thingID);
                    $thingCount>=1
                    )
then
	System.out.println("trigger "+$trigger.getTriggerID()+" been fire");
end

rule "summary of  true  result:number"
when
	$trigger:Trigger(type =="number")
	accumulate( MatchResult(triggerID==$trigger.triggerID,$thingID:thingID );
                    $thingCount : count($thingID);
                    $thingCount>=$trigger.number
                    )
then
	System.out.println("trigger "+$trigger.getTriggerID()+" been fire");
end
