package com.kii.extension.ruleengine.demo

import com.kii.extension.ruleengine.drools.entity.*;

global com.kii.extension.ruleengine.drools.entity.CurrThing currThing;



/////////////////////////////////////
//simple trigger 102,when:change
/////////////////////////////////////
rule "add trigger 102's  express "
when
    Trigger( $triggerID:triggerID==102,$things:things )
    CurrThing(thing memberOf $things) from currThing
    ThingStatus( $thingID:thingID memberOf $things,values["foo"]>10&&values["bar"]<0  )
then
	insertLogical(new MatchResult($triggerID));
end