package com.kii.extension.ruleengine.demo

import com.kii.extension.ruleengine.drools.entity.*;

global com.kii.extension.ruleengine.drools.entity.CurrThing currThing;



/////////////////////////////////////
//simple trigger 100,when:false to true
/////////////////////////////////////

rule "add trigger 100's  express "
when
    Trigger( $triggerID:triggerID=="100",$things:things  )
    CurrThing(thing memberOf $things) from currThing
    ThingStatusInRule( $thingID:thingID memberOf $things,(values["foo"]>10&&values["bar"]<0)  )
then
	insertLogical(new MatchResult($triggerID));
end


