package com.kii.extension.ruleengine.demo

import com.kii.extension.ruleengine.drools.entity.*;

global com.kii.extension.ruleengine.drools.entity.CurrThing currThing;


rule "show curr thing"
when
	$curr:CurrThing()
	$status:ThingStatus(thingID == $curr.thing)
then
	System.out.println(" curr thing :"+$status);
end


/////////////////////////////////////
//simple trigger 100,when:false to true
/////////////////////////////////////
rule "add trigger 100's  express "
when
    Trigger( $triggerID:triggerID==100,$things:things  )
    CurrThing(thing memberOf $things) from currThing
    ThingStatus( $thingID:thingID memberOf $things,(values["foo"]>10&&values["bar"]<0)  )
then
	insertLogical(new MatchResult($triggerID));
end

/////////////////////////////////////
//simple trigger 101,when:true
/////////////////////////////////////
rule "add trigger 101's  express "
when
    Trigger( $triggerID:triggerID==101,$things:things )
    CurrThing(thing memberOf $things) from currThing
    ThingStatus( $thingID:thingID memberOf $things,values["foo"]>10&&values["bar"]<0  )
then
	insertLogical(new MatchResult($triggerID));
end

/////////////////////////////////////
//simple trigger 102,when:change
/////////////////////////////////////
rule "add trigger 102's  express "
when
    Trigger( $triggerID:triggerID==102,$things:things )
    CurrThing(thing memberOf $things) from currThing
    ThingStatus( $thingID:thingID memberOf $things,values["foo"]>10&&values["bar"]<0  )
then
	insertLogical(new MatchResult($triggerID));
end


/////////////////////////////////////
//group trigger 200
/////////////////////////////////////
rule "add trigger 200's  express "
when
    Trigger( $triggerID:triggerID==200,$things:things )
    CurrThing(thing memberOf $things) from currThing
    ThingStatus( $thingID:thingID memberOf $things,values["foo"]>10&&values["bar"]<0  )
then
	insertLogical(new MemberMatchResult($triggerID,$thingID));
end

/////////////////////////////////////
//group trigger 201
/////////////////////////////////////
rule "add trigger 201's  express "
when
    Trigger( $triggerID:triggerID==201,$things:things )
    CurrThing(thing memberOf $things) from currThing
    ThingStatus( $thingID:thingID memberOf $things,values["foo"]>10&&values["bar"]<0  )
then
	insertLogical(new MemberMatchResult($triggerID,$thingID));
end


/////////////////////////////////////
//group trigger 202
/////////////////////////////////////
rule "add trigger 202's  express "
when
    Trigger( $triggerID:triggerID==202,$things:things )
    CurrThing(thing memberOf $things) from currThing
    ThingStatus( $thingID:thingID memberOf $things,values["foo"]>10&&values["bar"]<0  )
then
	insertLogical(new MemberMatchResult($triggerID,$thingID));
end

/////////////////////////////////////
//summary trigger 300
/////////////////////////////////////
rule "add trigger 300's  express "
when
    Trigger( $triggerID:triggerID==300,$things:things )
    CurrThing(thing memberOf $things) from currThing
    ThingStatus( $thingID:thingID memberOf $things,values["foo"]>10&&values["bar"]<0  )
then
	insertLogical(new MemberMatchResult($triggerID,$thingID));
end