package com.kii.extension.ruleengine.demo

import com.kii.extension.ruleengine.drools.entity.*;

global com.kii.extension.ruleengine.drools.entity.CurrThing currThing;


/////////////////////////////////////
//group trigger 200
/////////////////////////////////////
rule "add trigger 200's  express "
when
    Trigger( $triggerID:triggerID==200,$things:things )
    CurrThing(thing memberOf $things) from currThing
    ThingStatus( $thingID:thingID memberOf $things,values["foo"]>10&&values["bar"]<0  )
then
	insertLogical(new MemberMatchResult($triggerID,$thingID));
end

/////////////////////////////////////
//group trigger 201
/////////////////////////////////////

rule "add trigger 201's  express :true"
when
    Trigger( $triggerID:triggerID==201,$things:things )
    CurrThing(thing memberOf $things) from currThing
	ThingStatus( $thingID:thingID memberOf $things,values["foo"]>10&&values["bar"]<0  )
then
	System.out.println("add match result:"+$thingID);
	insertLogical(new MemberMatchResult($triggerID,$thingID));
end


/////////////////////////////////////
//group trigger 202
/////////////////////////////////////
rule "add trigger 202's  express "
when
    Trigger( $triggerID:triggerID==202,$things:things )
    CurrThing(thing memberOf $things) from currThing
    ThingStatus( $thingID:thingID memberOf $things,values["foo"]>10&&values["bar"]<0  )
then
	insertLogical(new MemberMatchResult($triggerID,$thingID));
end

/////////////////////////////////////
//summary trigger 300
/////////////////////////////////////
rule "add trigger 300's  express "
when
	Trigger($triggerID:triggerID,triggerID==300)
    SummaryValueMap( triggerID==$triggerID, numberMap["sum_foo"]>numberMap["count_bar"]  )
then
	System.out.println("fire summary trigger 300");
	insertLogical(new MatchResult($triggerID));
end