package com.kii.extension.ruleengine.demo

import com.kii.extension.ruleengine.thingtrigger.*;
import com.kii.extension.ruleengine.*;


rule "match summary value"
    when
       $match : SummaryValueMap( numberMap["sum_foo"] != 0  && numberMap["sum_bar"] != 0  )
    then

    	CommandExec exec=(CommandExec)kcontext.getKieRuntime().getEnvironment().get("exec");

    	exec.doExecute($match.getTriggerID());

end

rule "show trigger"
when
	$trigger:Trigger()
then
	System.out.println("list trigger:"+$trigger.getTriggerID());
end

rule "add trigger 1's  express "
when
    Trigger( $triggerID:triggerID==1,$things:things )
    $status:ThingStatus( $thingID:thingID memberOf $things )
then
	insertLogical(new MatchResult($triggerID,$thingID));
end

rule "add trigger 2's  express "
when
    Trigger($triggerID:triggerID==2,$things:things)
    ThingStatus( $thingID:thingID memberOf $things , status>1 )
then
	insertLogical(new MatchResult($triggerID,$thingID));
end

rule "add trigger 0's  express "
when
    Trigger($triggerID:triggerID==0,$things:things)
    $status:ThingStatus( $thingID:thingID memberOf $things , status>0 )
then
	insertLogical(new MatchResult($triggerID,$thingID));
end

rule "list result status"
when
	$result:MatchResult()
then
	System.out.println("result status:"+$result.getThingID());
end
