package com.kii.extension.sdk.entity.serviceextension;

public enum ThingWhenType {
	THING_CREATED,THING_ENABLED,THING_DISABLED,THING_USER_OWNER_ADDED,
	THING_GROUP_OWNER_ADDED,THING_USER_OWNER_REMOVED,THING_GROUP_OWNER_REMOVED,
	THING_FIELDS_UPDATED,THING_DELETED,THING_CONNECTED,THING_DISCONNECTED;
}
