package com.kii.extension.ruleengine.drools.rule

import com.kii.extension.ruleengine.drools.entity.*;
import com.kii.extension.ruleengine.store.trigger.TriggerGroupPolicyType;
global CurrThing currThing;



rule "summary of  true  result:all"
when
	$trigger:Trigger(policy ==TriggerGroupPolicyType.All,$triggerID:triggerID,$things:things)
    CurrThing(thing memberOf $things) from currThing
    $match:MemberMatchResult(triggerID==$triggerID)
	accumulate(MemberMatchResult(triggerID==$triggerID,$thingID:thingID);
                        $thingCount : count($thingID);
                        $thingCount==$trigger.things.size()
              )
then
	System.out.println("trigger all "+$trigger.getTriggerID()+" been fire");
	insertLogical(new MatchResult($triggerID));
end


rule "summary of  true  result:any  ->true"
when
	$trigger:Trigger(policy ==TriggerGroupPolicyType.Any,$triggerID:triggerID,$things:things)
    CurrThing(thing memberOf $things) from currThing
	accumulate( MemberMatchResult(triggerID==$triggerID,thingID memberOf  $things, $thingID:thingID );
                      $thingCount : count($thingID);
					  $thingCount>0
                  )
then
	System.out.println("trigger any true "+$trigger.getTriggerID()+" been fire");
	insertLogical(new MatchResult($triggerID));
end

rule "summary of  true  result:number"
when
	$trigger:Trigger(policy ==TriggerGroupPolicyType.Some,$triggerID:triggerID,$things:things)
    CurrThing(thing memberOf $things) from currThing
    $match:MemberMatchResult(triggerID==$triggerID)
	accumulate( MemberMatchResult(triggerID==$triggerID,$thingID:thingID );
                    $thingCount : count($thingID);
                    $thingCount>=$trigger.number
                    )
then
	System.out.println("trigger number  "+$trigger.getTriggerID()+" been fire");
	insertLogical(new MatchResult($triggerID));
end


rule "summary of  true  result:percent"
when
	$trigger:Trigger(policy ==TriggerGroupPolicyType.Percent,$triggerID:triggerID,$things:things)
    CurrThing(thing memberOf $things) from currThing
    $match:MemberMatchResult(triggerID==$triggerID)
	accumulate( MemberMatchResult(triggerID==$triggerID,$thingID:thingID );
                    $thingCount : count($thingID);
                    $thingCount>=$trigger.number*$things.size()/100
                    )
then
	System.out.println("trigger number  "+$trigger.getTriggerID()+" been fire");
	insertLogical(new MatchResult($triggerID));
end