package com.kii.extension.ruleengine.drools.rule

import com.kii.extension.ruleengine.drools.entity.*;
import com.kii.extension.ruleengine.drools.CommandExec;

global com.kii.extension.ruleengine.drools.entity.CurrThing currThing;

declare com.kii.extension.ruleengine.drools.entity.ThingStatusInRule
    @role( event )
	@timestamp( createAt )

    thingID : String @key
    values  : java.util.Map
	createAt: java.util.Date

end

