package com.kii.extension.ruleengine.demo

import com.kii.extension.ruleengine.drools.entity.*;

global CurrThing currThing;



/////////////////////////////////////
//simple trigger 103,when:change
/////////////////////////////////////
rule "add trigger 103's  express "
when
    Trigger( $triggerID:triggerID=="103",$things:things )
    CurrThing(thing memberOf $things) from currThing
    ThingStatusInRule( $thingID:thingID memberOf $things,values["foo"]>10&&values["bar"]<0  )
then
	insertLogical(new MatchResult($triggerID));
end