package com.kii.extension.ruleengine.demo

import com.kii.extension.ruleengine.drools.entity.*;




/////////////////////////////////////
//simple trigger 500,when:false to true
/////////////////////////////////////

rule "add trigger 500's  express "
	timer (cron:0/10 * * * * ?)
when
    // Trigger( $triggerID:triggerID=="500")
   // CurrThing(init == false)
then
	// insertLogical(new MatchResult($triggerID));
	System.out.println("the cron been fired:"+System.currentTimeMillis());
end


