package com.kii.extension.ruleengine.demo

import com.kii.extension.ruleengine.drools.entity.*;

global CurrThing currThing;



/////////////////////////////////////
//simple trigger 500,when:false to true
/////////////////////////////////////

rule "add trigger 500's  express "
	timer (cron:* 0/1 * * * ?)
when
    Trigger( $triggerID:triggerID=="500",$things:things  )
    CurrThing(thing memberOf $things) from currThing
    ThingStatusInRule( $thingID:thingID memberOf $things,(values["foo"]>10&&values["bar"]<0)  )
then
	insertLogical(new MatchResult($triggerID));
	System.out.println("the cron been fired:"+System.currentTimeMillis());
end


rule "add trigger 501's  express "
	timer (int: 0s 1m)
when
    Trigger( $triggerID:triggerID=="501",$things:things  )
    CurrThing(thing memberOf $things) from currThing
    ThingStatusInRule( $thingID:thingID memberOf $things,(values["foo"]>10&&values["bar"]<0)  )
then
	insertLogical(new MatchResult($triggerID));
	System.out.println("the interval been fired:"+System.currentTimeMillis());

end
