package com.kii.extension.ruleengine.demo

import com.kii.extension.ruleengine.drools.entity.*;

import com.kii.extension.ruleengine.drools.CommandExec;



/////////////////////////////////////
//simple trigger 701,when:change
/////////////////////////////////////
rule "add trigger 701's  express "
when
    $ext:ExternalCollect()
    $status:ThingStatusInRule( $thingID:thingID,getValue("foo")>10&&getNumValue("bar")<0&&$ext.getValue("name.abc")>0  )
then

    System.out.println("fire");
	MatchResult result=new MatchResult($thingID);
	result.setParam("a",$status.getValue("foo"));
	result.setParam("b",$status.getValue("bar"));
	result.setParam("c",$ext.getValue("name.abc"));
	insertLogical(result);

    CommandExec exec=(CommandExec)kcontext.getKieRuntime().getEnvironment().get("exec");
    exec.doExecute("701",result);

end