package com.kii.extension.ruleengine.demo

import com.kii.extension.ruleengine.drools.entity.*;




/////////////////////////////////////
//simple trigger 103,when:change
/////////////////////////////////////
rule "add trigger 100's  express "
when
    Thing($triggerID:triggerID=="100",$thingID:thingID)
    CurrThing(thing == $thingID)
    ThingStatusInRule( thingID==$thingID,values["foo"]>10&&values["bar"]<0  )
then
	insertLogical(new MatchResult($triggerID));
end

