package com.kii.extension.ruleengine.demo

import com.kii.extension.ruleengine.drools.entity.*;




rule "slide length mode  compute the summary of  fieldName value: funName"
when
	$trigger:Trigger(type =="summary",$triggerID:triggerID)
	$summary:Summary(triggerID==$triggerID ,$thingIDs:thingIDs, funName=="sum-length" ,$length:length)
	CurrThing(thing memberOf $thingIDs)
	accumulate( ThingStatusInRule(thingID memberOf $thingIDs , $status:values) over window:length( 10 );
                    $sum : sum($status.get($summary.getFieldName()))
                  )
then
	System.out.println("compute  sum summary by slide length"+$sum);
	insert(new SummaryResult($triggerID,$summary.getSummaryField(),$sum));
end


rule "slide time mode  compute the summary of  fieldName value: funName"
when
	$trigger:Trigger(type =="summary",$triggerID:triggerID)
	$summary:Summary(triggerID==$triggerID ,$thingIDs:thingIDs, funName=="sum-time" )
	CurrThing(thing memberOf $thingIDs)
	accumulate( ThingStatusInRule(thingID memberOf $thingIDs , $status:values) over window:time(1m);
                    $sum : sum($status.get($summary.getFieldName()))
                  )
then
	System.out.println("compute  sum summary by slide time "+$sum);
	insert(new SummaryResult($triggerID,$summary.getSummaryField(),$sum));
end
