package com.kii.extension.ruleengine.demo

import com.kii.extension.ruleengine.drools.entity.*;



/////////////////////////////////////
//group trigger 200
/////////////////////////////////////
rule "add trigger 200's  express "
when
    Trigger( $triggerID:triggerID=="200" )
    $group:Group(triggerID==$triggerID,$thingIDs:things)
    CurrThing(thing memberOf $thingIDs)
    $status:ThingStatusInRule( $thingID:thingID memberOf $thingIDs ,values["foo"]>10&&values["bar"]<0  )
then
	insertLogical(new MemberMatchResult($group,$status));
end

/////////////////////////////////////
//group trigger 201
/////////////////////////////////////

rule "add trigger 201's  express :true"
when
    Trigger( $triggerID:triggerID=="201" )
    $group:Group(triggerID==$triggerID,$thingIDs:things)
    CurrThing(thing memberOf $thingIDs)
    $status:ThingStatusInRule( $thingID:thingID memberOf $thingIDs,values["foo"]>10&&values["bar"]<0  )
then
	System.out.println("add match result:"+$thingID);
	insertLogical(new MemberMatchResult($group,$status));
end


/////////////////////////////////////
//group trigger 202
/////////////////////////////////////
rule "add trigger 202's  express "
when
    Trigger( $triggerID:triggerID=="202" )
    $group:Group(triggerID==$triggerID,$thingIDs:things)
    CurrThing(thing memberOf $thingIDs)
    $status:ThingStatusInRule( $thingID:thingID memberOf $thingIDs,values["foo"]>10&&values["bar"]<0  )
then
	insertLogical(new MemberMatchResult($group,$status));
end

/////////////////////////////////////
//summary trigger 300
/////////////////////////////////////
rule "add trigger 300's  express "
when
	Trigger($triggerID:triggerID,triggerID=="300")
    SummaryValueMap( triggerID==$triggerID, values["sum_foo"]>values["count_bar"]  )
then
	System.out.println("fire summary trigger 300");
	insertLogical(new MatchResult($triggerID));
end

/////////////////////////////////////
//summary trigger 400
/////////////////////////////////////
rule "add trigger 400's  express "
when
	Trigger($triggerID:triggerID,triggerID=="400")
    SummaryValueMap( triggerID==$triggerID, values["sum_foo"]>values["sum_bar"]  )
then
	System.out.println("fire summary trigger 400");
	insertLogical(new MatchResult($triggerID));
end