/*
package com.kii.extension.ruleengine.drools.rule

import com.kii.extension.ruleengine.drools.entity.*;




rule "put all thing spec status value to multipleMap"
	no-loop true
when
	$trigger:Trigger($triggerID:triggerID,type ==TriggerType.multiple)
	ThingStatusInRule( thingID == $thingID, $values:values)
    $map:MultiplesValueMap(triggerID==$triggerID)
then
	System.out.println("multiple trigger "+$trigger.getTriggerID()+" 's thing value "+$thingID+" name:"+$name+" value:"+$values);
	modify($map){
        	setFieldValueSet($name,$fieldSet,$values);
    };
end

*/

