package com.kii.extension.ruleengine.demo

import com.kii.extension.ruleengine.drools.entity.*;

global String currThing;


rule "summary of  true  result:all"
when
	$trigger:Trigger(type =="all",$triggerID:triggerID,$things:things)
	CurrThing(thingID memberOf $things)
	forall( MemberMatchResult(triggerID==$triggerID) )
then
	System.out.println("trigger all "+$trigger.getTriggerID()+" been fire");
	insertLogical(new MatchResult($triggerID));
end


rule "summary of  true  result:any"
when
	$trigger:Trigger(type =="any",$triggerID:triggerID,$things:things)
	CurrThing(thingID memberOf $things)
	exists MemberMatchResult(triggerID==$triggerID)
then
	System.out.println("trigger any "+$trigger.getTriggerID()+" been fire");
	insertLogical(new MatchResult($triggerID));
end

rule "summary of  true  result:number"
when
	$trigger:Trigger(type =="number",$triggerID:triggerID,$things:things)
	CurrThing(thingID memberOf $things)
	accumulate( MemberMatchResult(triggerID==$triggerID,$thingID:thingID );
                    $thingCount : count($thingID);
                    $thingCount>=$trigger.number
                    )
then
	System.out.println("trigger number  "+$trigger.getTriggerID()+" been fire");
	insertLogical(new MatchResult($triggerID));
end
