INSERT INTO `source` (`source_id`,`name`, `type`) VALUES (1,'Tag', 'Web');
INSERT INTO `source` (`source_id`,`name`, `type`) VALUES (2,'Thing', 'Web');
INSERT INTO `source` (`source_id`,`name`, `type`) VALUES (3,'UserGroup', 'Web');
INSERT INTO `source` (`source_id`,`name`, `type`) VALUES (4,'Permission', 'Web');
INSERT INTO `permission` (`source_id`, `name`, `action`) VALUES ('1', 'CreateTag', 'POST /tags/custom');
INSERT INTO `permission` (`source_id`, `name`, `action`) VALUES ('1', 'DeleteTag', 'DELETE /tags/custom/*');
INSERT INTO `permission` (`source_id`, `name`, `action`) VALUES ('1', 'SearchTag', 'GET /tags/search*');
INSERT INTO `permission` (`source_id`, `name`, `action`) VALUES ('1', 'SearchLocationTag', 'GET /tags/locations/*');
INSERT INTO `permission` (`source_id`, `name`, `action`) VALUES ('1', 'GetAllLocationTag', 'GET /tags/locations');
INSERT INTO `permission` (`source_id`, `name`, `action`) VALUES ('2', 'CreateThing', 'POST /things');
INSERT INTO `permission` (`source_id`, `name`, `action`) VALUES ('2', 'DeleteThing', 'DELETE /things/*');
INSERT INTO `permission` (`source_id`, `name`, `action`) VALUES ('2', 'SearchThing', 'GET /things/search*');
INSERT INTO `permission` (`source_id`, `name`, `action`) VALUES ('2', 'SearchThingType', 'GET /things/types/*');
INSERT INTO `permission` (`source_id`, `name`, `action`) VALUES ('2', 'SearchThingID', 'GET /things/*');
INSERT INTO `permission` (`source_id`, `name`, `action`) VALUES ('2', 'GetAllThingType', 'GET /things/types');
INSERT INTO `permission` (`source_id`, `name`, `action`) VALUES ('2', 'BindThingTag', 'POST /things/*/tags/*');
INSERT INTO `permission` (`source_id`, `name`, `action`) VALUES ('2', 'RemoveThingTag', 'DELETE /things/*/tags/*');
INSERT INTO `permission` (`source_id`, `name`, `action`) VALUES ('2', 'BindThingTagCustom', 'PUT /things/*/tags/custom/*');
INSERT INTO `permission` (`source_id`, `name`, `action`) VALUES ('2', 'RemoveThingCustomTag', 'DELETE /things/*/tags/custom/*');
INSERT INTO `permission` (`source_id`, `name`, `action`) VALUES ('3', 'CreateUserGroup', 'POST /usergroup');
INSERT INTO `permission` (`source_id`, `name`, `action`) VALUES ('3', 'DeleteUserGroup', 'DELETE /usergroup/*');
INSERT INTO `permission` (`source_id`, `name`, `action`) VALUES ('3', 'AddUserToGroup', 'POST /usergroup/*/user/*');
INSERT INTO `permission` (`source_id`, `name`, `action`) VALUES ('3', 'RemoveUserToGroup', 'DELETE /usergroup/*/user/*');
INSERT INTO `permission` (`source_id`, `name`, `action`) VALUES ('3', 'GetUserGroupDetail', 'GET /usergroup/*');
INSERT INTO `permission` (`source_id`, `name`, `action`) VALUES ('3', 'GetUserGroupList', 'GET /usergroup/list');
INSERT INTO `permission` (`source_id`, `name`, `action`) VALUES ('4', 'BindPermissionToUserGroup', 'POST /permission/*/userGroup/*');
INSERT INTO `permission` (`source_id`, `name`, `action`) VALUES ('4', 'RemovePermissionToUserGroup', 'DELETE /permission/*/userGroup/*');
INSERT INTO `permission` (`source_id`, `name`, `action`) VALUES ('4', 'GetUserGroupList', 'GET /permission/list');
INSERT INTO `permission` (`source_id`, `name`, `action`) VALUES ('4', 'GetUserGroupPermission', 'GET /permission/userGroup/*');
